version: '3.4'

services:
  mongodb:
    image: mongo
    container_name: "explorer_mongodb"
    volumes:
      - ../mongo/data/db:/data/db
  postgres:
    image: postgres:11.3-alpine
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: explorer
      POSTGRES_PASSWORD: example
    volumes:
      - ../postgres/data/:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  backend:
    ulimits:
      memlock: -1
    build:
      context: ../
      dockerfile: ${DOCKER_FILE}
      target: dev_env
      args:
        github_token: ${GITHUB_TOKEN}
    image: dev_image
    volumes:
      - "../:/explorer/"
    working_dir: /explorer
    entrypoint: ./scripts/start_dev.sh
    ports:
      - 8081:3001
    environment: &app-environment
      ENVIRONMENT: dev
      GITHUB_TOKEN: ${GITHUB_TOKEN}
  app_test:
    ulimits:
      memlock: -1
    image: "${BUILDER_IMAGE}"
    environment: *app-environment
  grabber:
    ulimits:
      memlock: -1
    build:
      context: ../
      dockerfile: ${DOCKER_FILE}
      target: dev_env
      args:
        github_token: ${GITHUB_TOKEN}
    image: dev_image
    volumes:
      - "../:/grabber/"
    working_dir: /grabber
    entrypoint: ./scripts/start_grabber.sh
    ports:
      - 8082:3002
    environment:
      ENVIROMENT: dev
      GITHUB_TOKEN: ${GITHUB_TOKEN}