version: '3.4'

services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    #environment:
    #  - MONGO_DATA_DIR=/data/db
    #  - MONGO_LOG_DIR=/dev/null
    volumes:
      - ../mongo/data/db:/data/db
  db:
    image: postgres:11.3-alpine
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: kaistarter
      POSTGRES_PASSWORD: example
    volumes:
      - ../postgres/data/:/var/lib/postgresql/data
  app:
    ulimits:
      memlock: -1
    build:
      context: ../
      dockerfile: ${DOCKER_FILE}
      target: dev_env
      args:
        github_token: ${GITHUB_TOKEN}
    image: dev_image
    volumes:
      - "../:/explorer/"
    working_dir: /explorer
    entrypoint: ./scripts/start_dev.sh
    ports:
      - 8081:3000
    environment: &app-environment
      ENVIRONMENT: dev
      GITHUB_TOKEN: ${GITHUB_TOKEN}
  app_test:
    ulimits:
      memlock: -1
    depends_on:
      - db
    image: "${BUILDER_IMAGE}"
    environment: *app-environment
