version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: "explorer-mongodb"
    volumes:
      - ../mongo/data/db:/data/db
    restart: always
    ports:
      - 27017:27017
  postgres:
    image: postgres:11.9
    container_name: "explorer-postgres"
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: explorer
      POSTGRES_PASSWORD: example
    volumes:
      - ../postgres-explorer:/var/lib/postgresql/data
  backend:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: kardiachain/backend-explorer
    ports:
      - 8000:3000
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: "api"
    depends_on:
      - grabber
      - mongodb
      - postgres
  grabber:
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: kardiachain/backend-explorer
    ports:
      - 8001:3000
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    command: "grabber -m mongodb:27017 -u http://10.10.0.251:8551 --log-level info -f true"