version: '3.4'

services:
  redis:
    image: redis:latest
    container_name: "explorer-redis"
    ports:
      - 6379:6379
    restart: always
  mongodb:
    image: mongo:latest
    container_name: "explorer-mongodb"
    volumes:
      - ../mongo/data/db:/data/db
    restart: always
    ports:
      - 27017:27017
    command: "--wiredTigerCacheSizeGB 4 --wiredTigerCollectionBlockCompressor zstd --wiredTigerJournalCompressor zstd"
  backend:
    build:
      context: .
    image: kardiachain/backend-explorer
    container_name: "explorer-backend"
    ports:
      - 8000:3000
    command: "api"
    volumes:
      - .env.sample:/go/bin/.env
    depends_on:
      - grabber
      - mongodb
  grabber:
    image: kardiachain/backend-explorer
    container_name: "explorer-grabber"
    volumes:
      - .env.sample:/go/bin/.env
    command: "grabber"
  backfill:
    image: kardiachain/backend-explorer
    container_name: "explorer-backfill"
    volumes:
      - .env.sample:/go/bin/.env
    command: "backfill"
    depends_on:
      - grabber
      - mongodb
  verifier:
    image: kardiachain/backend-explorer
    container_name: "explorer-verifier"
    volumes:
      - .env.sample:/go/bin/.env
    command: "verifier"
    depends_on:
      - grabber
      - mongodb
  receipts:
    image: kardiachain/backend-explorer
    container_name: "explorer-receipts"
    volumes:
      - .env.sample:/go/bin/.env
    command: "receipts"
    depends_on:
      - grabber
      - mongodb
  watcher:
    image: kardiachain/backend-explorer
    container_name: "explorer-watcher"
    volumes:
      - .env.sample:/go/bin/.env
    command: "watcher"
    depends_on:
      - grabber
      - mongodb