name: Linter
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.7'

      - name: Config git for private modules
        env:
          TOKEN: ${{ secrets.ACTION_GITHUB_SECRET }}
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/kardiachain".insteadOf "https://github.com/kardiachain"

      - name: Cache dependencies
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Fetch dependencies
        env:
          GO111MODULE: "on"
          GOPRIVATE: "github.com/kardiachain"
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Vendor dependencies
        run: go mod vendor

      - name: Lint
        uses: reviewdog/action-golangci-lint@v1
        env:
          GOROOT: ""
        with:
          github_token: ${{ secrets.ACTION_GITHUB_SECRET }}
          golangci_lint_flags: "--modules-download-mode vendor --timeout 30m -v"
          reporter: github-pr-review
